-- LAYER / Campus 3D Print Lab
-- Supabase schema for authentication profiles, products, campus orders,
-- order items and custom fabrication requests.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  campus_id text,
  user_type text check (user_type in ('Student','Faculty','Staff')),
  department text,
  year_of_study text,
  mobile text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null,
  price numeric(10,2) not null check (price >= 0),
  material text,
  finish text,
  lead_time text,
  tag text,
  description text,
  image_url text,
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  total numeric(10,2) not null check (total >= 0),
  status text not null default 'SUBMITTED',
  pickup_status text not null default 'PENDING',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.custom_print_requests (
  id uuid primary key default gen_random_uuid(),
  request_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  requester_name text not null,
  department text,
  material text,
  quantity integer not null default 1 check (quantity > 0),
  model_path text,
  original_filename text,
  notes text,
  status text not null default 'UNDER REVIEW',
  estimated_grams numeric(10,2),
  estimated_minutes integer,
  estimated_cost numeric(10,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Automatically create a public profile when a user registers.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (
    id, full_name, campus_id, user_type, department, year_of_study, mobile
  ) values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name',''),
    new.raw_user_meta_data ->> 'campus_id',
    nullif(new.raw_user_meta_data ->> 'user_type',''),
    new.raw_user_meta_data ->> 'department',
    nullif(new.raw_user_meta_data ->> 'year_of_study',''),
    new.raw_user_meta_data ->> 'mobile'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();
drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products
for each row execute procedure public.set_updated_at();
drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders
for each row execute procedure public.set_updated_at();
drop trigger if exists custom_print_requests_updated_at on public.custom_print_requests;
create trigger custom_print_requests_updated_at before update on public.custom_print_requests
for each row execute procedure public.set_updated_at();

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.custom_print_requests enable row level security;

drop policy if exists "Profiles are visible to owner" on public.profiles;
drop policy if exists "Profiles are editable by owner" on public.profiles;
drop policy if exists "Active products are public" on public.products;
drop policy if exists "Users can view own orders" on public.orders;
drop policy if exists "Users can create own orders" on public.orders;
drop policy if exists "Users can view own order items" on public.order_items;
drop policy if exists "Users can add items to own orders" on public.order_items;
drop policy if exists "Users can view own fabrication requests" on public.custom_print_requests;
drop policy if exists "Users can create own fabrication requests" on public.custom_print_requests;

create policy "Profiles are visible to owner"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create policy "Profiles are editable by owner"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Active products are public"
on public.products for select
to anon, authenticated
using (active = true);

create policy "Users can view own orders"
on public.orders for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create own orders"
on public.orders for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can view own order items"
on public.order_items for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id and o.user_id = auth.uid()
  )
);

create policy "Users can add items to own orders"
on public.order_items for insert
to authenticated
with check (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id and o.user_id = auth.uid()
  )
);

create policy "Users can view own fabrication requests"
on public.custom_print_requests for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create own fabrication requests"
on public.custom_print_requests for insert
to authenticated
with check (auth.uid() = user_id);

-- Private model upload bucket.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('models', 'models', false, 26214400, null)
on conflict (id) do nothing;

drop policy if exists "Users upload models to own folder" on storage.objects;
drop policy if exists "Users can read own uploaded models" on storage.objects;

create policy "Users upload models to own folder"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'models'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can read own uploaded models"
on storage.objects for select
to authenticated
using (
  bucket_id = 'models'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Initial catalogue. Replace image_url with Storage/CDN URLs when real photos are uploaded.
insert into public.products (id,name,category,price,material,finish,lead_time,tag,description,stock,featured)
values
('p1','Arc Phone Stand','DESK / UTILITY',149,'PLA+','MATTE','SAME DAY*','BESTSELLER','A sculptural low-profile stand for phones on study desks, lab benches and charging stations.',20,true),
('p2','Campus Key Tag','CAMPUS EDITION',49,'PLA+','DUAL TONE','SAME DAY*','PERSONALISE','Personalised campus key tags for names, departments, labs, events and student teams.',50,true),
('p3','Hex Desk Organiser','DESK / UTILITY',229,'PLA+','FINE','1 DAY','MODULAR','Modular geometric storage for pens, markers, cables and small electronic components.',12,false),
('p4','Gear Motion Model','ENGINEERING',299,'PLA+','FINE','1–2 DAYS','STEM','A tactile motion model for mechanism demonstrations, classrooms and engineering presentations.',10,true),
('p5','Mini Planter — Fold','DECOR / GIFT',179,'PLA+','TEXTURED','1 DAY','DESIGN PICK','A folded geometric planter with a strong architectural silhouette for desks and indoor spaces.',15,false),
('p6','Cable Dock Trio','DESK / UTILITY',99,'TPU / PLA+','STANDARD','SAME DAY*','UTILITY','A three-slot cable dock that stops charging leads from disappearing behind desks and benches.',25,false),
('p7','Miniature Campus Block','CAMPUS EDITION',349,'PLA+','FINE','2–3 DAYS','COLLECTIBLE','A stylised architectural miniature for souvenirs, presentations, gifting and display.',8,true),
('p8','Project Enclosure S','ENGINEERING',199,'PETG','STANDARD','1–2 DAYS','PROJECT READY','Compact project enclosure for controller boards, sensors and prototype electronics.',10,false)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  price = excluded.price,
  material = excluded.material,
  finish = excluded.finish,
  lead_time = excluded.lead_time,
  tag = excluded.tag,
  description = excluded.description,
  stock = excluded.stock,
  featured = excluded.featured;
