const cfg=window.LAYER_SUPABASE||{},client=(window.supabase&&cfg.url&&!cfg.url.includes("YOUR_"))?window.supabase.createClient(cfg.url,cfg.anonKey):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
let user,profile,products=[],editing=null;
async function guard(){
 if(!client)return deny("Supabase is not configured.");
 let {data}=await client.auth.getSession();user=data.session?.user;if(!user)return deny("Please login to LAYER before opening the admin console.");
 let {data:p}=await client.from("profiles").select("*").eq("id",user.id).maybeSingle();profile=p;
 if(profile?.role!=="admin")return deny("This account does not have admin permission.");
 $("#adminName").textContent=profile.full_name||user.email;await Promise.all([loadProducts(),loadOrders(),loadCoupons(),loadSettings()]);
}
function deny(t){document.body.innerHTML=`<main class="denied"><h1>Admin access required.</h1><p>${t}</p><a href="index.html">Return to LAYER</a></main>`}
$$("[data-tab]").forEach(b=>b.onclick=()=>{let tab=b.dataset.tab;$$("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));$$(".admin-view").forEach(v=>v.classList.toggle("active",v.dataset.view===tab));$("#adminTitle").textContent=tab[0].toUpperCase()+tab.slice(1)});
async function loadProducts(){let {data,error}=await client.from("products").select("*").order("created_at",{ascending:false});if(error)return alert(error.message);products=data||[];$("#productAdminCount").textContent=`${products.length} objects`;$("#productRows").innerHTML=products.map(p=>`<tr><td class="object-cell"><img src="${(p.image_urls?.[0]||p.image_url||"assets/phone-stand.svg")}"><div><b>${p.name}</b><span>${p.category} · ${p.sku||p.id}</span></div></td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.estimated_delivery_days||1} day(s)</td><td><span class="pill ${p.active?'live':''}">${p.active?'LIVE':'HIDDEN'}</span></td><td><button class="row-action" onclick="editProduct('${p.id}')">EDIT</button></td></tr>`).join("")}
$("#newProduct").onclick=()=>openEditor();
$("#closeEditor").onclick=()=>$("#productEditor").close();
function openEditor(p=null){editing=p;let f=$("#productForm");f.reset();f.elements.id.value=p?.id||"";$("#editorTitle").textContent=p?"Edit object.":"New object.";["name","sku","category","price","compare_at_price","material","finish","tag","stock","estimated_delivery_days","weight_grams","description"].forEach(k=>{if(p&&f.elements[k])f.elements[k].value=p[k]??""});f.elements.active.checked=p?p.active:true;f.elements.featured.checked=!!p?.featured;f.elements.customizable.checked=!!p?.customizable;$("#productEditor").showModal()}
window.editProduct=id=>openEditor(products.find(p=>p.id===id));
function safeName(s){return s.toLowerCase().replace(/[^a-z0-9._-]+/g,"-")}
async function uploadPhotos(id,files){let urls=[];for(const file of [...files].slice(0,5)){let path=`${id}/${Date.now()}-${safeName(file.name)}`;let {error}=await client.storage.from("product-images").upload(path,file,{upsert:false});if(error)throw error;let {data}=client.storage.from("product-images").getPublicUrl(path);urls.push(data.publicUrl)}return urls}
$("#productForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget),id=f.get("id")||`prd-${Date.now().toString(36)}`,photoFiles=$("#productPhotos").files;let urls=editing?.image_urls||[];try{if(photoFiles.length)urls=await uploadPhotos(id,photoFiles)}catch(err){return alert(err.message)}
 let payload={id,name:f.get("name"),sku:f.get("sku")||null,category:f.get("category"),price:+f.get("price"),compare_at_price:f.get("compare_at_price")?+f.get("compare_at_price"):null,material:f.get("material"),finish:f.get("finish"),tag:f.get("tag"),stock:+f.get("stock")||0,estimated_delivery_days:+f.get("estimated_delivery_days")||1,weight_grams:f.get("weight_grams")?+f.get("weight_grams"):null,description:f.get("description"),active:f.get("active")==="on",featured:f.get("featured")==="on",customizable:f.get("customizable")==="on",image_urls:urls,image_url:urls[0]||editing?.image_url||null};
 let {error}=await client.from("products").upsert(payload);if(error)return alert(error.message);$("#productEditor").close();await loadProducts()};
async function loadOrders(){let [{data:o},{data:p}]=await Promise.all([client.from("orders").select("*").order("created_at",{ascending:false}).limit(100),client.from("profiles").select("id,full_name,campus_id")]);let pm=Object.fromEntries((p||[]).map(x=>[x.id,x]));$("#orderRows").innerHTML=(o||[]).map(x=>`<tr><td><b>${x.order_number}</b><br><small>${x.delivery_mode||""}</small></td><td>${pm[x.user_id]?.full_name||"User"}<br><small>${pm[x.user_id]?.campus_id||""}</small></td><td>${money(x.total)}</td><td><select class="status-select" onchange="updateOrder('${x.id}','payment_status',this.value)">${["PENDING","PAID","FAILED","REFUNDED"].map(s=>`<option ${x.payment_status===s?'selected':''}>${s}</option>`).join("")}</select></td><td><select class="status-select" onchange="updateOrder('${x.id}','status',this.value)">${["SUBMITTED","CONFIRMED","PRINTING","POST PROCESSING","READY FOR PICKUP","OUT FOR DELIVERY","COMPLETED","CANCELLED"].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join("")}</select></td><td>${new Date(x.created_at).toLocaleDateString("en-IN")}</td></tr>`).join("")}
window.updateOrder=async(id,k,v)=>{let {error}=await client.from("orders").update({[k]:v}).eq("id",id);if(error)alert(error.message)};
async function loadCoupons(){let {data}=await client.from("coupons").select("*").order("created_at",{ascending:false});$("#couponRows").innerHTML=(data||[]).map(c=>`<div class="coupon-row"><div><b>${c.code}</b><span>${c.discount_type==="percent"?c.discount_value+"%":money(c.discount_value)} · min ${money(c.min_order)} · used ${c.used_count||0}${c.usage_limit?"/"+c.usage_limit:""}</span></div><span class="pill ${c.active?'live':''}">${c.active?'ACTIVE':'OFF'}</span></div>`).join("")||"No coupons yet."}
$("#couponForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget),p=Object.fromEntries(f.entries());p.code=p.code.toUpperCase();p.discount_value=+p.discount_value;p.min_order=+p.min_order||0;p.max_discount=p.max_discount?+p.max_discount:null;p.usage_limit=p.usage_limit?+p.usage_limit:null;p.active=p.active==="true";let {error}=await client.from("coupons").upsert(p,{onConflict:"code"});if(error)return alert(error.message);e.currentTarget.reset();await loadCoupons()};
async function loadSettings(){let {data}=await client.from("store_settings").select("*").eq("key","checkout").maybeSingle(),v=data?.value||{};let f=$("#paymentForm");f.elements.payment_link_url.value=v.payment_link_url||"";f.elements.upi_id.value=v.upi_id||"";f.elements.payee_name.value=v.payee_name||"";f.elements.payment_instructions.value=v.payment_instructions||"";f.elements.allow_pay_at_desk.checked=v.allow_pay_at_desk!==false}
$("#paymentForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget),value={payment_link_url:f.get("payment_link_url")||"",upi_id:f.get("upi_id")||"",payee_name:f.get("payee_name")||"LAYER Campus 3D Lab",payment_instructions:f.get("payment_instructions")||"",allow_pay_at_desk:f.get("allow_pay_at_desk")==="on"};let {error}=await client.from("store_settings").upsert({key:"checkout",value});if(error)return alert(error.message);alert("Checkout settings saved.")};
guard();